create table giderler (
  id bigint generated by default as identity primary key,
  tarih timestamptz,
  donem integer,
  kategori text,
  k numeric default 0,
  aciklama text,
  created_at timestamptz default now()
);

create table gelirler (
  id bigint generated by default as identity primary key,
  tarih timestamptz,
  donem integer,
  tur text,
  k numeric default 0,
  aciklama text,
  created_at timestamptz default now()
);

create table birikimler (
  id bigint generated by default as identity primary key,
  tarih timestamptz,
  tur text,
  miktar numeric default 0,
  aciklama text,
  created_at timestamptz default now()
);

create table borc_alacak (
  id bigint generated by default as identity primary key,
  tarih timestamptz,
  kisi text,
  tur text,
  tutar numeric default 0,
  aciklama text,
  odendi boolean default false,
  created_at timestamptz default now()
);

-- Herkese okuma/yazma izni (kişisel kullanım)
alter table giderler enable row level security;
alter table gelirler enable row level security;
alter table birikimler enable row level security;
alter table borc_alacak enable row level security;

create policy "Herkes okuyabilir" on giderler for all using (true) with check (true);
create policy "Herkes okuyabilir" on gelirler for all using (true) with check (true);
create policy "Herkes okuyabilir" on birikimler for all using (true) with check (true);
create policy "Herkes okuyabilir" on borc_alacak for all using (true) with check (true);
