create table birikim_hareketler (
  id bigint generated by default as identity primary key,
  tarih timestamptz not null,
  tur text not null,
  alt_tip text,
  miktar numeric default 0,
  islem_tl numeric default 0,
  kur numeric,
  aciklama text,
  created_at timestamptz default now()
);

alter table birikim_hareketler enable row level security;

create policy "Sadece giris yapanlar" on birikim_hareketler
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
