-- =====================================================================
-- YENİ MİMARİ — hesaplar (master) + hesap_hareketler (birleşik defter)
-- =====================================================================
-- Bu script SADECE yeni tabloları oluşturur ve 15 hesabı tohumlar.
-- Mevcut tablolar (giderler, gelirler, nk_transferler, birikim_hareketler,
-- borc_kalemler, borc_harcamalar) bu aşamada DOKUNULMADAN kalır — veri
-- taşıma (migration) ayrı bir script ile, ekranlar geçirildikçe yapılacak.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) TABLOLAR
-- ---------------------------------------------------------------------

create table hesaplar (
  id bigint generated by default as identity primary key,
  ad text not null,
  ust_hesap_id bigint references hesaplar(id),
  -- ANA_HESAP: Ana Hesap (rollup, kendi hareketi olmaz)
  -- banka / nakit: Ana Hesap'ın somut alt hesapları (gerçek hareketler burada)
  -- birikim: kasa içi varlıklar (Birikim TL kökü dahil)
  -- yatirim: kasadan çıkıp bir işe yatırılan paralar (bakiye = net kâr/zarar)
  -- borc: kişi+döviz cinsi başına alacak/borç takibi
  tip text not null check (tip in ('ANA_HESAP','banka','nakit','birikim','yatirim','borc')),
  doviz_cinsi text not null default 'TL',
  aktif boolean not null default true,
  sira integer,
  aciklama text,
  created_at timestamptz default now()
);

create table hesap_hareketler (
  id bigint generated by default as identity primary key,
  hesap_id bigint not null references hesaplar(id),
  -- Transferlerde (çift kayıt) diğer ucu işaret eder; tekli gider/gelirde null
  karsi_hesap_id bigint references hesaplar(id),
  -- Eşleşen iki satırı birbirine bağlar (transferler için zorunlu, tekli kayıtlarda null)
  grup_id uuid,
  tarih timestamptz not null,
  donem integer,
  -- Hesabın KENDİ biriminde değişim (+artış / -azalış); transferde işaretler
  -- duruma göre simetrik (biri + biri -) ya da asimetrik (ikisi de aynı yönde,
  -- örn. yatırım hesaplarına giriş/çıkışta) olabilir — şema bunu zorlamaz.
  tutar numeric not null default 0,
  tur text not null check (tur in ('gider','gelir','transfer')),
  kategori text,
  -- Döviz/emtia hesapları için: o anki kur ve TL karşılığı (raporlama amaçlı)
  kur numeric,
  islem_tl numeric,
  aciklama text,
  sira integer,
  created_at timestamptz default now()
);

create index idx_hesaplar_ust_hesap_id on hesaplar(ust_hesap_id);
create index idx_hesap_hareketler_hesap_id on hesap_hareketler(hesap_id);
create index idx_hesap_hareketler_grup_id on hesap_hareketler(grup_id);
create index idx_hesap_hareketler_donem on hesap_hareketler(donem);


-- ---------------------------------------------------------------------
-- 2) RLS — projedeki diğer tablolarla aynı politika deseni
-- ---------------------------------------------------------------------

alter table hesaplar enable row level security;
alter table hesap_hareketler enable row level security;

create policy "Sadece giris yapanlar" on hesaplar
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Sadece giris yapanlar" on hesap_hareketler
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');


-- ---------------------------------------------------------------------
-- 3) TOHUM VERİ — 15 hesap
--    (Ana Hesap + Banka + Nakit) + (Birikim TL kökü + 11 alt hesap)
-- ---------------------------------------------------------------------

-- Kökler
insert into hesaplar (ad, ust_hesap_id, tip, doviz_cinsi, sira) values
  ('Ana Hesap',    null, 'ANA_HESAP', 'TL', 1),
  ('Birikim (TL)', null, 'birikim',   'TL', 2);

-- Ana Hesap'ın somut alt hesapları (Banka / Nakit)
insert into hesaplar (ad, ust_hesap_id, tip, doviz_cinsi, sira)
select 'Banka', id, 'banka', 'TL', 1 from hesaplar where ad = 'Ana Hesap'
union all
select 'Nakit', id, 'nakit', 'TL', 2 from hesaplar where ad = 'Ana Hesap';

-- Birikim (TL)'nin alt hesapları — birikim tipi (varlık değeri takibi)
insert into hesaplar (ad, ust_hesap_id, tip, doviz_cinsi, sira)
select v.ad, b.id, 'birikim', v.doviz, v.sira
from (values
  ('ALT (H)', 'ALT', 1),
  ('ALT (F)', 'ALT', 2),
  ('GMS (H)', 'GMS', 3),
  ('USD',     'USD', 4),
  ('EUR',     'EUR', 5),
  ('GBP',     'GBP', 6)
) as v(ad, doviz, sira)
cross join (select id from hesaplar where ad = 'Birikim (TL)') as b;

-- Birikim (TL)'nin alt hesapları — yatırım tipi (net kâr/zarar takibi)
insert into hesaplar (ad, ust_hesap_id, tip, doviz_cinsi, sira)
select v.ad, b.id, 'yatirim', 'TL', v.sira
from (values
  ('İnşaat',          7),
  ('Palandora',       8),
  ('Hayvancılık',     9),
  ('Şirketi Hayriyye',10),
  ('ALIM-SATIM',      11)
) as v(ad, sira)
cross join (select id from hesaplar where ad = 'Birikim (TL)') as b;

-- Birikim (TL)'nin alt hesapları — borç tipi (kişi × döviz cinsi başına alacak takibi)
insert into hesaplar (ad, ust_hesap_id, tip, doviz_cinsi, sira)
select v.ad, b.id, 'borc', v.doviz, v.sira
from (values
  ('Bilal Dayı (€)',           'EUR', 12),
  ('Ahmet Abim (ALT)',         'ALT', 13),
  ('Burak Aydın (ALT)',        'ALT', 14),
  ('Abdullah Altuntaş (ALT)',  'ALT', 15),
  ('Alpaslan Abim (ALT)',      'ALT', 16),
  ('Emirhan Kaya',             'ALT', 17),
  ('Osman Demirkoparan (ALT)', 'ALT', 18)
) as v(ad, doviz, sira)
cross join (select id from hesaplar where ad = 'Birikim (TL)') as b;

-- Kontrol — hiyerarşiyi gözden geçirin:
-- select h.id, h.ad, h.tip, h.doviz_cinsi, u.ad as ust_hesap, h.sira
-- from hesaplar h left join hesaplar u on u.id = h.ust_hesap_id
-- order by coalesce(h.ust_hesap_id, h.id), h.ust_hesap_id nulls first, h.sira;
