-- Gider ve gelirlere hesap kolonu ekle (K=Banka, N=Nakit)
alter table giderler add column if not exists hesap text default 'K';
alter table gelirler add column if not exists hesap text default 'K';

-- NK transfer tablosu
create table if not exists nk_transferler (
  id bigint generated by default as identity primary key,
  tarih timestamptz not null,
  donem integer,
  k numeric default 0,  -- bankaya yüklenen (nakit→banka)
  n numeric default 0,  -- bankadan çekilen (banka→nakit)
  aciklama text,
  created_at timestamptz default now()
);

alter table nk_transferler enable row level security;

create policy "Sadece giris yapanlar" on nk_transferler
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
