create table borc_hareketler (
  id bigint generated by default as identity primary key,
  tarih timestamptz,
  kisi text not null,
  hareket_tipi text not null, -- 'alindi' veya 'odendi'
  tutar numeric default 0,
  doviz_miktar numeric,
  doviz_birim text,
  aciklama text,
  created_at timestamptz default now()
);

alter table borc_hareketler enable row level security;

create policy "Sadece giris yapanlar" on borc_hareketler
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
