-- Ekstre Kes artık bir ara state (bekleyen ekstre) oluşturur; gerçek banka
-- gider kaydı sadece "Öde" denildiğinde işlenir.

create table borc_ekstreler (
  id bigint generated by default as identity primary key,
  hesap_id bigint not null references borc_hesaplar(id) on delete cascade,
  donem integer not null,
  tutar numeric not null default 0,
  kesildi_tarih date not null default current_date,
  odendi boolean not null default false,
  odendi_tarih date,
  created_at timestamptz not null default now()
);

alter table borc_ekstreler enable row level security;

create policy "Sadece giris yapanlar" on borc_ekstreler
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

alter table borc_kalemler add column if not exists ekstre_id bigint references borc_ekstreler(id) on delete set null;
